# Starts the SpeedTest using MySQL as the backend database. 

version: '2.4'

services:
  htapui:
    depends_on:
      htapmaster:
        condition: service_healthy
    container_name: htapui
    hostname: htapui
    image: intersystemsdc/irisdemo-demo-htap:ui-version-2.0.3
    ports:
    - "10000:4200" # Where Node Will be listening

  mysqldb: 
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    hostname: mysqldb
    init: true
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpass

  htapmaster:
    depends_on: 
      - mysqldb
    container_name: htapmaster
    hostname: htapmaster
    init: true
    image: intersystemsdc/irisdemo-demo-htap:master-version-2.0.3
    ports:
      - "10002:8080" # Where Springboot Will be listening
    environment:
      - START_CONSUMERS=true
      - INGESTION_THREADS_PER_WORKER=2
      - INGESTION_BATCH_SIZE=1000
      - INGESTION_JDBC_URL=jdbc:mysql://mysqldb:3306/SpeedTest
      - INGESTION_JDBC_USERNAME=root
      - INGESTION_JDBC_PASSWORD=mysqlpass
      - CONSUMER_JDBC_URL=jdbc:mysql://mysqldb:3306/SpeedTest
      - CONSUMER_JDBC_USERNAME=root
      - CONSUMER_JDBC_PASSWORD=mysqlpass
      - CONSUMER_THREADS_PER_WORKER=1
      - CONSUMER_TIME_BETWEEN_QUERIES_IN_MILLIS=0

  ingest-worker1:
    depends_on: 
      htapmaster:
        condition: service_healthy
    container_name: ingest-worker1
    hostname: ingest-worker1
    init: true
    image: intersystemsdc/irisdemo-demo-htap:mysql-jdbc-ingest-worker-version-2.0.3
    ports:
      - "10003:8080" # Where Springboot Will be listening
    environment:
      - MASTER_HOSTNAME=htapmaster
      - MASTER_PORT=8080

  query-worker1:
    depends_on: 
      htapmaster:
        condition: service_healthy
    container_name: query-worker1
    hostname: query-worker1
    init: true
    image: intersystemsdc/irisdemo-demo-htap:mysql-jdbc-query-worker-version-2.0.3
    ports:
      - "10004:8080" # Where Springboot Will be listening
    environment:
      - MASTER_HOSTNAME=htapmaster
      - MASTER_PORT=8080
