apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-worker-deployment
  labels:
    app: ingestion-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-worker-pod
  template:
    metadata:
      labels:
        app: ingestion-worker-pod
    spec:
      nodeSelector:
        speedtest/node-type: ingest
      containers:
      - name: ingestion-worker-container
        image: intersystemsdc/irisdemo-demo-htap:iris-jdbc-ingest-worker-version-2.7.2
        ports:
        - containerPort: 8080
        env:
        - name: MASTER_HOSTNAME
          value: "htapmaster"
        - name: MASTER_PORT
          value: "8080"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-worker-deployment
  labels:
    app: query-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-worker-pod
  template:
    metadata:
      labels:
        app: query-worker-pod
    spec:
      nodeSelector:
        speedtest/node-type: query
      containers:
      - name: query-worker-container
        image: intersystemsdc/irisdemo-demo-htap:iris-jdbc-query-worker-version-2.7.2
        ports:
        - containerPort: 8080
        env:
        - name: MASTER_HOSTNAME
          value: "htapmaster"
        - name: MASTER_PORT
          value: "8080"
